### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by pabs3** [iakat/archivebot-dashboard-repeater#2]
I modified the README and sent a pull request without checking that the project does not yet have a license, so technically what I did was not yet legal.

It would be great if you could [choose an open source license](https://choosealicense.com/) so that the project could be contributed to and or redistributed.

**Comment by pabs3** [comment]
Since ArchiveBot is MIT licensed, maybe go with that too.

Personally I would normally choose AGPL (or other GNU licenses), but going with what the ArchiveTeam community uses might be best.

**Comment by iakat** [comment]
closed by 6aa20907cd6f25ac861b1ed82abf39877fb2d4bd
